name: Test Deployment

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Build and publish
      run: ./gradlew clean build modrinth --info --stacktrace
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        MODRINTH_VERSION_TYPE: 'alpha'
        MODRINTH_CHANGELOG_TEXT: 'Available at https://github.com/litetex-oss/template-placeholder/blob/dev/CHANGELOG.md<br/><i>Please note that this is a SNAPSHOT which might be unstable</i>'

    - name: Upload mod files
      uses: actions/upload-artifact@v4
      with:
        name: mod-files
        path: |
          build/devlibs/*-sources.jar
          build/libs/*.jar
          !build/libs/*-sources.jar
          !build/libs/*-javadoc.jar
        if-no-files-found: error

    - name: Publish to OSSRH
      run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --info --stacktrace
      env:
        MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        SONATYPE_MAVEN_CENTRAL_PORTAL_USERNAME: ${{ secrets.SONATYPE_MAVEN_CENTRAL_PORTAL_USERNAME }}
        SONATYPE_MAVEN_CENTRAL_PORTAL_TOKEN: ${{ secrets.SONATYPE_MAVEN_CENTRAL_PORTAL_TOKEN }}
