name: Update yarn

on:
  schedule:
    - cron: '47 1 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  UPDATE_BRANCH: update-yarn

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Required because otherwise there are always changes detected when executing diff/rev-list
          fetch-depth: 0
      
      - name: Init Git
        run: |
          git config --global user.email "164098849+litetex-oss-bot@users.noreply.github.com"
          git config --global user.name "litetex-oss-bot"

      - name: Update
        id: update
        run: |
          yarnVersion=$(curl --fail -L https://maven.fabricmc.net/net/fabricmc/yarn/maven-metadata.xml | grep -oP "(?<=<latest>)[^<]+")

          echo "Getting PR target branch"
          pr_target_branch=$(git branch --show-current)
          echo "PR target branch is $pr_target_branch"
          echo "pr_target_branch=$pr_target_branch" >> $GITHUB_OUTPUT
          
          echo "Deleting local branch that will contain the updates - if present"
          git branch -D ${{ env.UPDATE_BRANCH }} || true

          echo "Creating update branch"
          git checkout -b ${{ env.UPDATE_BRANCH }}

          echo "Replacing yarn version"
          sed -i "s/^\(yarn_mappings\s*=\s*\).*\$/\1$yarnVersion/" gradle.properties

          if [[ "$(git status --porcelain)" == "" ]]; then
            echo "No files to commit"
            echo "abort=1" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Performing commit"
          git add -A
          git commit -m "Yarn $yarnVersion"

          echo "Pushing update branch"
          git push -f -u origin ${{ env.UPDATE_BRANCH }}

          echo "abort=0" >> $GITHUB_OUTPUT
          
      - name: pull-request
        if: steps.update.outputs.abort == 0
        env:
          # Don't use default token as no workflows are run otherwise
          # https://github.com/orgs/community/discussions/65321#discussioncomment-6861423
          GH_TOKEN: ${{ secrets.BOT_PR_PAT }}
        run: |
          gh_pr_up() { 
            gh pr create -H "${{ env.UPDATE_BRANCH }}" "$@" || (git checkout "${{ env.UPDATE_BRANCH }}" && gh pr edit "$@")
          }
          gh_pr_up -B "${{ steps.update.outputs.pr_target_branch }}" \
            --title "Yarn update" \
            --body "An automated PR to update [yarn](https://github.com/FabricMC/yarn).<br>[Source](https://maven.fabricmc.net/net/fabricmc/yarn/maven-metadata.xml)"
